* wordle-fetch
- Basic idea is to re-implement Steve Wart's data fetcher for Wordle,
  but using nicely parallelized Haskell instead of JavaScript. (Note:
  Copy of Steve's code is included here as a reference.)
- Anticipate using:
  - Network.Wreq for HTTP client library
  - Date libraries as used in my own mqtt-logger app
  - 
- Can start with some basic code from the rainforest app that I had
  also started previously, using the Wreq library there as well.
- Using "naive" approach from
  https://chrisdone.com/posts/measuring-duration-in-haskell/, since
  we're not too worried about system time changing in the middle of
  things.
** DONE Remember to use nix-shell to have zlib available
** DONE get date range strings in appropriate format
** DONE fix build failure from newer GHC / libs
- Current setup is trying to use GHC 9.4.6 instead of 9.0.2 (used
  previously), and one of the dependencies that worked before has
  changed and caused breakage. <2023-09-28 Thu>
  - Data.DateTime was used for dateOffset, but looks like it hasn't
    kept up with other libraries.
  - No current version of addMinutes, so I think we need:
    "addUTCTime nominalDay date" to add one day's offset
